/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xtkj_jni_capture_ServerVideoDecoder */

#ifndef _Included_cn_xtkj_jni_capture_ServerVideoDecoder
#    define _Included_cn_xtkj_jni_capture_ServerVideoDecoder
#    ifdef __cplusplus
extern "C" {
#    endif
/*
 * Class:     cn_xtkj_jni_capture_ServerVideoDecoder
 * Method:    initResource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL
Java_cn_xtkj_jni_capture_ServerVideoDecoder_initResource(JNIEnv*,
                                                         jobject,
                                                         jint);

/*
 * Class:     cn_xtkj_jni_capture_ServerVideoDecoder
 * Method:    open
 * Signature: (Ljava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_cn_xtkj_jni_capture_ServerVideoDecoder_open(JNIEnv*,
                                                                        jobject,
                                                                        jstring,
                                                                        jint,
                                                                        jint,
                                                                        jint,
                                                                        jint,
                                                                        jint);

/*
 * Class:     cn_xtkj_jni_capture_ServerVideoDecoder
 * Method:    takeState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL
Java_cn_xtkj_jni_capture_ServerVideoDecoder_takeState(JNIEnv*, jobject, jint);

/*
 * Class:     cn_xtkj_jni_capture_ServerVideoDecoder
 * Method:    takeInfo
 * Signature: (I)Lcn/xtkj/jni/capture/data/VideoInfo;
 */
JNIEXPORT jobject JNICALL
Java_cn_xtkj_jni_capture_ServerVideoDecoder_takeInfo(JNIEnv*, jobject, jint);

/*
 * Class:     cn_xtkj_jni_capture_ServerVideoDecoder
 * Method:    decodeToMatRef
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL
Java_cn_xtkj_jni_capture_ServerVideoDecoder_decodeToMatRef(JNIEnv*,
                                                           jobject,
                                                           jint);

/*
 * Class:     cn_xtkj_jni_capture_ServerVideoDecoder
 * Method:    release
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL
Java_cn_xtkj_jni_capture_ServerVideoDecoder_release(JNIEnv*, jobject, jint);

#    ifdef __cplusplus
}
#    endif
#endif
